Role check
NeRpi/iTechArtPractice pull request #10
Opened 2023-06-21 15:25 UTC by NeRpi

2023-06-21 15:32 UTC, NeRpi commented on server/src/middleware/jwt.middleware.ts
> +    req.user = new UserDto(userData);
to do this, I extended the Request type in express/index.d.ts

declare global{
    namespace Express {
        export interface Request {
            user?: UserDto;
        }
    }
}

2023-06-21 16:47 UTC, Daniil-Zaichuk-iTechArt approved these changes

2023-06-21 16:47 UTC, Daniil-Zaichuk-iTechArt commented on server/src/dto/user.dto.ts
> +  public id?: string;
all fields are public by default. So you can omit this modifier

2023-06-21 16:47 UTC, Daniil-Zaichuk-iTechArt commented on server/src/middleware/verify.is.super.admin.middleware.ts
> +const verifyIsSuperAdminMiddleware = async (
Don't think that creating middleware for each role is good idea;)

2023-06-21 16:47 UTC, Daniil-Zaichuk-iTechArt commented on server/src/middleware/verify.is.super.admin.middleware.ts
> +      return next(ApiError.internal("Access denied!"));
just send 403 Forbidden. No need to throw an error

2023-06-23 08:26 UTC, Daniil-Zaichuk-iTechArt approved these changes

2023-06-23 15:07 UTC, Daniil-Zaichuk-iTechArt requested changes

2023-06-23 15:07 UTC, Daniil-Zaichuk-iTechArt commented on server/src/repositories/role.repo.ts
> +  async createRole(roleName: Roles) {
We want to be able to create new roles not to dublicate existing

2023-06-23 15:07 UTC, Daniil-Zaichuk-iTechArt commented on server/src/services/auth.service.ts
> +      id: userDto.id,
I'd name it as userId just to make it clear to which entity it belongs

2023-06-23 15:07 UTC, Daniil-Zaichuk-iTechArt commented on tasks/228.js
> +    for (let i = 0; i < nums.length; i++) {
Try not to use C-like fors in JS. We have a lot of iteration methods (forEach, reduce, map, etc)

2023-06-23 15:07 UTC, Daniil-Zaichuk-iTechArt commented on tasks/228.js
> +    let f = nums.at(0);
let f = nums[0]
keep it simple:)

2023-06-23 15:07 UTC, Daniil-Zaichuk-iTechArt commented on tasks/228.js
> +    let f = nums.at(0);
"f" is "first"?

2023-06-23 15:07 UTC, Daniil-Zaichuk-iTechArt commented on tasks/2448.js
> +    let right = pairArray.length - 1;
JS community doen't have strong opinion about ';', but you definitely need to be consistent with using it

2023-06-27 11:54 UTC, Daniil-Zaichuk-iTechArt approved these changes

2023-06-29 13:12 UTC, merged